site_name: MkDocs

nav:
#  - Home: 00_index.md
  - Template: 01_OracleLinux9.md
  - DNS: 02_dns.md
  - Proxy: 03_squid.md
  - Nginx: 04_nginx.md
  - Repo: 05_local_repository.md
  - SFTP: 06_sftp.md
  - PaceMaker: 07_pacemaker.md
  - MicroK8S: 08_microk8s.md
  - Nexus: 09_local_registry.md
  - Redis: 10_redis.md
  - ActiveMQ: 11_activemq.md
  - Artemis: 12_artemis.md
  - Tomcat: 13_tomcat.md
  - Jasperreport: 14_jasperreport.md
  - Wildfly: 15_wildfly.md
  - Keepalive: 16_keepalive.md
  - HAProxy: 17_haproxy.md
  - SiteRecovery: 18_site_recovery.md
  - LifeRecovery: 19_life_recovery.md

theme:
  name: material
  features:
#    - navigation.tabs
#    - navigation.sections
    - toc.integrate
#    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: es
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: indigo
      accent: purple
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: indigo
      accent: lime

plugins:
  - search

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
